import type { NextPage } from 'next'
import Head from 'next/head'
import Box from "../src/screens/Box"
import styles from "../styles/home.module.scss"
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box />
    </div>
      
  
  )
}

export default Home
