import type { NextPage } from 'next'
import Head from 'next/head'
import Title from "components/Title"
import Box from "components/Box"
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title />
      <Box />
    </div>
  )
}

export default Home
